<?php

$info = array(

  // Available colors and color labels used in theme.
  'fields' => array(
  'color1' => t('Base Color 1'),
	'color2' => t('Base Color 2'),
	'color3' => t('Base Color 3'),
	'color4' => t('Base Color 4'),
	'color5' => t('Base Color 5'),  
  ),
  // Pre-defined color schemes.
  'schemes' => array(
  'default' => array(
    'title' => t('Iris Gray Scale (Base)'),
      'colors' => array(
        'color1' => '#dddddd',
		'color2' => '#aaaaaa',
		'color3' => '#777777',
		'color4' => '#333333',
		'color5' => '#000000',       
      ),
    ),	
	'ch810222' => array(
      'title' => t('Color Hunter - 810222'),
      'colors' => array(
        'color1' => '#011314',
		'color2' => '#008EA8',
		'color3' => '#3EF3FF',
		'color4' => '#FFFFFE',
		'color5' => '#0089FF',        
      ),
    ),
	'ch810059' => array(
      'title' => t('Color Hunter - 810059'),
      'colors' => array(
        'color1' => '#060405',
		'color2' => '#4A1000',
		'color3' => '#9E3000',
		'color4' => '#FF4600',
		'color5' => '#FFED95',        
      ),
    ),
	'ch809966' => array(
      'title' => t('Color Hunter - 809966'),
      'colors' => array(
        'color1' => '#99735D',
		'color2' => '#FF6E2B',
		'color3' => '#F3B87E',
		'color4' => '#CAC5C0',
		'color5' => '#97A5B6',        
      ),
    ),
	'ch809947' => array(
      'title' => t('Color Hunter - 809947'),
      'colors' => array(
        'color1' => '#1F0D0D',
		'color2' => '#854352',
		'color3' => '#D1735C',
		'color4' => '#FFBB7C',
		'color5' => '#E8C3B1',        
      ),
    ),
	'ch809553' => array(
      'title' => t('Color Hunter - 809553'),
      'colors' => array(
        'color1' => '#2B3031',
		'color2' => '#798074',
		'color3' => '#52574C',
		'color4' => '#F1F0EF',
		'color5' => '#BB9089',        
      ),
    ),
	'ch444619' => array(
      'title' => t('Color Hunter - 444619'),
      'colors' => array(
        'color1' => '#5F5941',
		'color2' => '#F69200',
		'color3' => '#FFF784',
		'color4' => '#FFFFE3',
		'color5' => '#C14D00',        
      ),
    ),
	'ch750810' => array(
      'title' => t('Color Hunter - 750810'),
      'colors' => array(
        'color1' => '#6E2300',
		'color2' => '#CD1C00',
		'color3' => '#F58300',
		'color4' => '#FFEDD3',
		'color5' => '#98A922',        
      ),
    ),
	'ch311679' => array(
      'title' => t('Color Hunter - 311679'),
      'colors' => array(
        'color1' => '#4D3200',
		'color2' => '#D30C00',
		'color3' => '#EFD000',
		'color4' => '#FFFFA4',
		'color5' => '#7EAA00',        
      ),
    ),
	'ch431485' => array(
      'title' => t('Color Hunter - 431485'),
      'colors' => array(
        'color1' => '#650B00',
		'color2' => '#CA0000',
		'color3' => '#F58800',
		'color4' => '#FFCCAD',
		'color5' => '#92A11B',        
      ),
    ),
	'ch722963' => array(
      'title' => t('Color Hunter - 722963'),
      'colors' => array(
        'color1' => '#2C0000',
		'color2' => '#76450F',
		'color3' => '#DD9C2E',
		'color4' => '#FFE36F',
		'color5' => '#B3660E',        
      ),
    ),	
	'ch753104' => array(
      'title' => t('Color Hunter - 753104'),
      'colors' => array(
        'color1' => '#2C0000',
		'color2' => '#7B4712',
		'color3' => '#AF6329',
		'color4' => '#C1975B',
		'color5' => '#FFE9C1',        
      ),
    ),	
	'ch785188' => array(
      'title' => t('Color Hunter - 785188'),
      'colors' => array(
        'color1' => '#2C0000',
		'color2' => '#690000',
		'color3' => '#882800',
		'color4' => '#CF0400',
		'color5' => '#FFC771',        
      ),
    ),	
	'ch502729' => array(
      'title' => t('Color Hunter - 502729'),
      'colors' => array(
        'color1' => '#554E41',
		'color2' => '#CCCABD',
		'color3' => '#F4FFFF',
		'color4' => '#F5F2DE',
		'color5' => '#AA6E6A',        
      ),
    ),	
	'ch800798' => array(
      'title' => t('Color Hunter - 800798'),
      'colors' => array(
        'color1' => '#606C79',
		'color2' => '#B0AA97',
		'color3' => '#CECDBB',
		'color4' => '#F1F5F1',
		'color5' => '#87A0A9',        
      ),
    ),	
	'ch809892' => array(
      'title' => t('Color Hunter - 809892'),
      'colors' => array(
        'color1' => '#CFC9CA',
		'color2' => '#FFFFFF',
		'color3' => '#FFFFFF',
		'color4' => '#FBF3EB',
		'color5' => '#AF7F7E',        
      ),
    ),	
	'ch810328' => array(
      'title' => t('Color Hunter - 810328'),
      'colors' => array(
        'color1' => '#743600',
		'color2' => '#F09311',
		'color3' => '#E4B471',
		'color4' => '#FBCC86',
		'color5' => '#FAE3C4',        
      ),
    ),
	'ch809913' => array(
      'title' => t('Color Hunter - 809913'),
      'colors' => array(
        'color1' => '#0E0905',
		'color2' => '#46270A',
		'color3' => '#8F3A00',
		'color4' => '#8F723D',
		'color5' => '#CEB587',        
      ),
    ),
	'ch809695' => array(
      'title' => t('Color Hunter - 809695'),
      'colors' => array(
        'color1' => '#3D3D3D',
		'color2' => '#191919',
		'color3' => '#636363',
		'color4' => '#898989',
		'color5' => '#C8C8C8',        
      ),
    ),
	'ch808858' => array(
      'title' => t('Color Hunter - 808858'),
      'colors' => array(
        'color1' => '#181818',
		'color2' => '#797979',
		'color3' => '#FFFFFF',
		'color4' => '#FFFFFF',
		'color5' => '#C7C7C7',        
      ),
    ),
	'ch808857' => array(
      'title' => t('Color Hunter - 808857'),
      'colors' => array(
        'color1' => '#284563',
		'color2' => '#FFFFFF',
		'color3' => '#FFFFFF',
		'color4' => '#D1D1CE',
		'color5' => '#959FA9',        
      ),
    ),
	'ch808586' => array(
      'title' => t('Color Hunter - 808586'),
      'colors' => array(
        'color1' => '#114047',
		'color2' => '#246F78',
		'color3' => '#5C7987',
		'color4' => '#225464',
		'color5' => '#8FA1AE',        
      ),
    ),
	'ch808520' => array(
      'title' => t('Color Hunter - 808520'),
      'colors' => array(
        'color1' => '#BD2E00',
		'color2' => '#FF5800',
		'color3' => '#FB6115',
		'color4' => '#E8B669',
		'color5' => '#F7F1E9',        
      ),
    ),
	'ch808521' => array(
      'title' => t('Color Hunter - 808521'),
      'colors' => array(
        'color1' => '#842400',
		'color2' => '#FF5C00',
		'color3' => '#F2631F',
		'color4' => '#FEFDFA',
		'color5' => '#EFBF7A',        
      ),
    ),
	'ch808519' => array(
      'title' => t('Color Hunter - 808519'),
      'colors' => array(
        'color1' => '#9C3200',
		'color2' => '#FA7617',
		'color3' => '#E0B573',
		'color4' => '#F6ECDE',
		'color5' => '#C59D6F',        
      ),
    ),
	'ch808347' => array(
      'title' => t('Color Hunter - 808347'),
      'colors' => array(
        'color1' => '#1C0D00',
		'color2' => '#462B00',
		'color3' => '#9A5B00',
		'color4' => '#F7FFFF',
		'color5' => '#FFAE4D',        
      ),
    ),
  ),


  // Images to copy over.
  'copy' => array( 
	'logo.png',
  ),

  // CSS files (excluding @import) to rewrite with new color scheme.
  'css' => array(
    'color/color.css',
  ),

  // Gradient definitions.
  'gradients' => array(
  ),

  // Color areas to fill (x, y, width, height).
  'fill' => array(
  ),

  // Coordinates of all the theme slices (x, y, width, height)
  // with their filename as used in the stylesheet.
  'slices' => array(  
  ),

  // Reference color used for blending. Matches the base.png's colors.
  'blend_target' => '#ffffff',

  // Preview files.
  'preview_image' => 'color/preview.png',
  'preview_css' => 'color/preview.css',
  'preview_js' => 'color/preview.js',
  'preview_html' => 'color/preview.html',
  
  'base_image' => 'color/preview.png',
);
