; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules

projects[] = "admin_menu"
projects[] = "advanced_help"
projects[] = "backup_migrate"
projects[] = "bootstrap_api"
projects[] = "bootstrap_optimizer"
projects[] = "browscap"
projects[] = "coder"
projects[] = "ctools"
projects[] = "captcha"
projects[] = "ckeditor"
projects[] = "colorbox"
projects[] = "context"
projects[] = "date"
projects[] = "smart_ip"
projects[] = "entity"
projects[] = "extlink"
projects[] = "fb_social"
projects[] = "fboauth"
projects[] = "fontyourface"
projects[] = "google_analytics"
projects[] = "grammar_parser_lib"
projects[] = "imagecache_actions"
projects[] = "imce"
projects[] = "imce_wysiwyg"
projects[] = "jquery_update"
projects[] = "less"
projects[] = "libraries"
projects[] = "locationmap"
projects[] = "media"
projects[] = "oauth"
projects[] = "pathauto"
projects[] = "print"
projects[] = "purl"
projects[] = "redirect"
projects[] = "retina_images"
projects[] = "socialmedia"
projects[] = "stringoverrides"
projects[] = "termstatus"
projects[] = "token"
projects[] = "transliteration"
projects[] = "twitter"
projects[] = "twitter_block"
projects[] = "user_dashboard"
projects[] = "views"
projects[] = "views_bootstrap"
projects[] = "views_slideshow"
projects[] = "weather_block"
projects[] = "webform"
projects[] = "widgets"
projects[] = "wysiwyg"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cute_slider][download][type] = ""
projects[cute_slider][download][url] = ""
projects[cute_slider][location] = ""
projects[cute_slider][type] = "module"
projects[cute_slider][version] = "2.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[md_slider][download][type] = ""
projects[md_slider][download][url] = ""
projects[md_slider][location] = ""
projects[md_slider][type] = "module"
projects[md_slider][version] = "2.6"

 Themes
projects[] = "bootstrap"

projects[slash][download][type] = ""
projects[slash][download][url] = ""
projects[slash][type] = "theme"

; Libraries

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.4/ckeditor_3.4.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "http://getbootstrap.com/2.3.2/assets/bootstrap.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"

libraries[dompdf][download][type] = "get"
libraries[dompdf][download][url] = "https://github.com/dompdf/dompdf/archive/master.zip"
libraries[dompdf][directory_name] = "dompdf"
libraries[dompdf][type] = "library"

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "https://jquery-ui.googlecode.com/files/jquery-ui-1.8.24.zip"
libraries[jquery_ui][directory_name] = "jquery_ui"
libraries[jquery_ui][type] = "library"

libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[jquery.cycle][download][type] = "git"
libraries[jquery.cycle][download][url] = "https://github.com/malsup/cycle.git"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

libraries[lessphp][download][type] = "git"
libraries[lessphp][download][url] = "https://github.com/leafo/lessphp.git"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"
