<?php
// $Id$

/**
 * @file
 * Addition feeds module so that it will do garbage collection.
 *
 * @author Wayne Eaker <wayne@zengenuity.com>
 */

/**
 * Implements hook_feeds_plugins().
 */
function feeds_gc_feeds_plugins() {
  $info = array();
  $info['FeedsNodeProcessorGC'] = array(
    'name' => 'Node Processor with Garbage Collection',
    'description' => 'Functions like the Node Processor, but will unpublish content no longer in the feed.',
    'handler' => array(
      'parent' => 'FeedsNodeProcessor',
      'class' => 'FeedsNodeProcessorGC',
      'file' => 'FeedsNodeProcessorGC.inc',
      'path' => drupal_get_path('module', 'feeds_gc'),
    ),
  );
  return $info;
}
