/**
 * Implements hook_file_url_alter().
 */
function fh_cdn_file_url_alter(&$original_uri) {

  $scheme = file_uri_scheme($original_uri);

  // If the current URI is an absolute or protocol-relative URI, return
  // immediately.
  if (($scheme && ($scheme == 'http' || $scheme == 'https'))
      || drupal_substr($original_uri, 0, 2) == '//'
     )
  {
    return;
  }
  elseif ($scheme) {
      // Only alter URLs for local stream wrappers. If a file is served
    // remotely, it doesn't make sense to serve it from a CDN.
    $local_schemes = array_keys(file_get_stream_wrappers(STREAM_WRAPPERS_LOCAL));
    if (!in_array($scheme, $local_schemes)) {
      return;
    }

    // Attempt to get an external URL using the appropriate wrapper.
    if ($wrapper = file_stream_wrapper_get_instance_by_uri($original_uri)) {
      $uri = str_replace($GLOBALS['base_url'] . '/', '', $wrapper->getExternalUrl());

      $original_uri = variable_get('fh_cdn', 'https://CDN.MYDOMAIN.COM') . '/' . $uri;
      return;
    }
    else {
      return;
    }
  }
  else {
    $original_uri = variable_get('fh_cdn', 'http://cdn.freighthouse.nyc') . '/' . $original_uri;
  }

}
